print(dir())
name = input('What is your name ? ')
print('Hello World! and ', name)
print('Hello', name, ', Welcome to Python!')
print('Hello', name + ', Welcome to Python!')
print(dir())
del(name)
print('After deleting')
print(dir())
